plugins {
    id 'net.ltgt.errorprone' version '5.1.0'
    id 'com.diffplug.spotless' version '7.2.1'
    id 'jacoco'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'net.ltgt.errorprone'
    apply plugin: 'com.diffplug.spotless'
    apply plugin: 'jacoco'

    group = project.property("GROUP_ID")
    version = project.property("VERSION_NAME")

    repositories {
        gradlePluginPortal()
        mavenCentral()
    }

    spotless {
        java {
            googleJavaFormat('1.27.0')
        }
    }

    jacocoTestReport {
        dependsOn test

        reports {
            html.required = true
            xml.required = true
        }
    }

    dependencies {
        errorprone("com.google.errorprone:error_prone_core:2.42.0")
        testImplementation("junit:junit:4.13.2")
        testImplementation("com.google.truth:truth:1.4.1")
    }

    tasks.withType(JavaCompile) {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11

        options.encoding = "UTF-8"
    }
}